# Generated by Django 2.1.2 on 2018-10-19 01:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SignIn', '0003_auto_20181018_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50, verbose_name='Course Seeking Help For')),
                ('reason', models.CharField(max_length=50, verbose_name='Reason for Visit')),
                ('rating', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(max_length=1000, null=True)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='schoolId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('Y00\\d{6}', 'School ID does not match the specified format')], verbose_name='Y Number'),
        ),
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SignIn.Student'),
        ),
    ]
