# Generated by Django 2.1.2 on 2018-11-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignIn', '0007_auto_20181025_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='courseoffer',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='CourseOffer',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
