# Generated by Django 2.1.2 on 2018-11-03 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignIn', '0008_auto_20181101_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
