# Generated by Django 2.1.2 on 2018-11-01 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseoffer',
            old_name='employee',
            new_name='user',
        ),
    ]
