# Generated by Django 2.1.2 on 2018-11-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20181101_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employeeId',
        ),
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
