# Generated by Django 2.1.2 on 2018-11-04 19:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashboard', '0004_auto_20181101_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('h0600', models.BooleanField(default=False)),
                ('h0700', models.BooleanField(default=False)),
                ('h0800', models.BooleanField(default=False)),
                ('h0900', models.BooleanField(default=False)),
                ('h1000', models.BooleanField(default=False)),
                ('h1100', models.BooleanField(default=False)),
                ('h1200', models.BooleanField(default=False)),
                ('h1300', models.BooleanField(default=False)),
                ('h1400', models.BooleanField(default=False)),
                ('h1500', models.BooleanField(default=False)),
                ('h1600', models.BooleanField(default=False)),
                ('h1700', models.BooleanField(default=False)),
                ('h1800', models.BooleanField(default=False)),
                ('h1900', models.BooleanField(default=False)),
                ('h2000', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
