# Generated by Django 2.1.2 on 2018-11-04 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20181104_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='dayOfWeek',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dayOfWeek',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
