# Generated by Django 2.1.2 on 2018-11-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_auto_20181104_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='h2000',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='h2000',
        ),
    ]
