# Generated by Django 2.1.2 on 2018-11-07 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_timeoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='status',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
