# Generated by Django 2.1.3 on 2018-11-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_auto_20181107_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='comment',
            field=models.CharField(blank=True, max_length=280, null=True, verbose_name='Comment'),
        ),
    ]
