# Generated by Django 2.1.2 on 2018-11-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_auto_20181108_1031'),
        ('Dashboard', '0012_auto_20181108_2257'),
    ]

    operations = [
    ]
