# Generated by Django 2.1.2 on 2018-11-10 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_auto_20181109_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='status',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
